apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: "{{ .Values.image }}:{{ .Values.tag }}"
        env:
        - name: COUNTRY
          value: "{{ .Values.COUNTRY }}"
        - name: ANOTHERVALUE
          value: "ANOTHER VALUE"
        ports:
        - containerPort: {{ .Values.port }}
