apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 5
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', "exit 1"]
      restartPolicy: Never
      containers:
      - name: helloworld
        image: "{{ .Values.image }}:{{ .Values.tag }}"
        env:
        - name: COUNTRY
          value: "{{ .Values.COUNTRY }}"
        - name: ANOTHERVALUE
          value: "ANOTHER VALUE"
        ports:
        - containerPort: {{ .Values.port }}
