apiVersion: v1
data:
  script.sh: |-
    echo "RUNNING TEST"
    echo "TEST Passed"
kind: ConfigMap
metadata:
  name: script-configmap
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: script-job
  name: script-job
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  containers:
    - command:
        - sh
        - /opt/script/script.sh
      image: 'alpine/git'
      name: script
      volumeMounts:
        - mountPath: /opt/script
          name: script-configmap
          readOnly: false
  restartPolicy: Never
  volumes:
    - configMap:
        name: script-configmap
      name: script-configmap
