apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  containers:
  - name: myapp-container
    image: 'debian'
    env:
    - name: COUNTRY
      value: "{{ .Values.COUNTRY }}"
    - name: MYVALUE
      value: "{{ .Values.MYVALUE }}"
    command: ["/bin/sh"]
    args: ["-c", "env; exit 1"]
  restartPolicy: Never
